### ISSUE TITLE
FT_Err_Invalid_Argument

### ISSUE THREAD

**Issue by flames519** [PistonDevelopers/freetype-sys#112]
![image](https://github.com/PistonDevelopers/freetype-sys/assets/48267811/4ccbe5b2-6b19-47e9-a35d-602c018cfefd)
 
It should be '* mut * mut' instead of '* mut'

**Comment by mrobinson** [comment]
It seems this issue can be closed after #113?

**Comment by waywardmonkeys** [comment]
@bvssvni This can be closed.
