### ISSUE TITLE
Add a feature/environment variable to opt-out of pkg-config

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/freetype-sys#14]
On OSX, I have problem where pkg-config looks up a version of FreeType belonging to the Mono framework, which is built for another target platform. To fix this, I have to override "freetype-sys" through Cargo and change the main method of build.rs into:

```Rust
fn main() {
    println!("cargo:rustc-flags=-l freetype:dylib");
    /*
    match pkg_config::find_library("freetype2") {
        Ok(_) => return,
        Err(_) => {
            if cfg!(windows) {
                println!("cargo:rustc-flags=-l freetype-6:dylib");
            } else {
                println!("cargo:rustc-flags=-l freetype:dylib");
            }
        }
    }
    */
}
```

It would be nice if there was a feature/environment variable to disable pkg-config.

**Comment by tomaka** [comment]
Or you can just tell Cargo how to find the library without changing the build script: http://doc.crates.io/build-script.html#overriding-build-scripts

**Comment by bvssvni** [comment]
@tomaka I remember you made a post about this! Had completely forgotten it.
