### ISSUE TITLE
the download links for windows libfreetype and zlib 404s.

### ISSUE THREAD

**Issue by tbm2** [PistonDevelopers/freetype-sys#37]
[might work for 32bit](http://sourceforge.net/projects/gnuwin32/files/freetype/2.3.5-1/freetype-2.3.5-1-setup.exe/download)

[64bit](http://lvserver.ugent.be/gtk-win64/gtk3-runtime/gtk3-runtime-3.14.13-2015-07-03-ts-win64.exe)

**Comment by Rickasaurus** [comment]
This didn't seem to work for me. There's no freetype.lib in "C:\Program Files\GTK3-Runtime Win64\bin"

**Comment by jhasse** [comment]
The MSYS2 binaries should now be used instead, makes life a lot easier. The README doesn't include download links for freetype and zlib anymore.
