### ISSUE TITLE
Library name is ignored and freetype-6 is always used instead

### ISSUE THREAD

**Issue by kryptan** [PistonDevelopers/freetype-sys#38]
I have the following .cargo/config:
```
[target.x86_64-pc-windows-gnu.freetype]
rustc-link-search = ["C:/msys64/mingw64/lib"]
rustc-link-lib = ["freetype.dll"]
root = "C:/msys64/mingw64/lib"
```
I am expecting that it will try to link to `C:/msys64/mingw64/lib/libfreetype.dll.a` however it always tries to link to `libfreetype-6.a` (which doesn't exist) regardless of the `rustc-link-lib` value. I have to copy & rename `libfreetype.dll.a` to `libfreetype-6.a` to make it work.

**Comment by retep998** [comment]
>however it always tries to link to libfreetype-6.a (which doesn't exist) regardless of the rustc-link-lib value. 

This is actually a Cargo bug (https://github.com/rust-lang/cargo/issues/2042) which was recently fixed. Please update to the latest nightly.

**Comment by bvssvni** [comment]
Reopen if this is still a problem.
