### ISSUE TITLE
Build freetype in build script

### ISSUE THREAD

**Issue by FredrikNoren** [PistonDevelopers/freetype-sys#50]
As title. See https://github.com/Eljay/assimp-sys for an example of how it can be done (essentially he's keeping the actual library as a submodule and then just building it with cmake-rs in the build.rs script).

Doing it that way, you can (as a user of this library) get started without installing freetype first, as it will be built as part of the cargo build. Or if you have a local install you can also take advantage of that.

**Comment by indiv0** [comment]
This would also allow the library to be statically linked in the final executable.

**Comment by nox** [comment]
This would help Servo to switch to this crate, too.

**Comment by Dominaezzz** [comment]
What would it take to get this work? Are there any other good examples to facilitate a PR? The link in the first comment isn't valid anymore.

**Comment by Dominaezzz** [comment]
I have figured out how to do this. Would a PR for this be accepted? (I don't want to have re-implement `freetype-rs` if I don't have to)

**Comment by Dominaezzz** [comment]
Looks this is done already in the build script so this issue can be closed.

**Comment by bvssvni** [comment]
Closing
