### ISSUE TITLE
Can't compile with MSVC ABI and GnuWin32 freetype.lib

### ISSUE THREAD

**Issue by Earlz** [PistonDevelopers/freetype-sys#51]
So, I did as the instructions on the readme says, it finds the library correctly, but then gives me a ton of missing symbol errors:

<pre>
   Compiling testgui v0.1.0 (file:///C:/dev/testgui)
error: linking with `link.exe` failed: exit code: 1120
note: "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC/bin\\amd64\\link.exe" "/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC/lib\\amd64" "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\x64" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\dev\\testgui\\target\\debug\\testgui.0.o" "/OUT:C:\\dev\\testgui\\target\\debug\\testgui.exe" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:C:\\dev\\testgui\\target\\debug" "/LIBPATH:C:\\dev\\testgui\\target\\debug\\deps" "/LIBPATH:C:\\Program Files (x86)\\GnuWin32\\lib" "/LIBPATH:C:\\dev\\testgui\\target\\debug\\build\\libz-sys-521f51dd8fade4c2\\out/lib" "/LIBPATH:C:\\dev\\testgui\\target\\debug\\build\\miniz-sys-f1c39e8e406fa25f\\out" "/LIBPATH:C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib" "/LIBPATH:C:\\dev\\testgui\\.rust\\bin\\x86_64-pc-windows-msvc" "/LIBPATH:C:\\dev\\testgui\\bin\\x86_64-pc-windows-msvc" "C:\\dev\\testgui\\target\\debug\\deps\\libconrod-116addbd19a314e7.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libfind_folder-8918d1206dae2083.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libpiston_window-ef7b6dfa617a6c78.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libglutin_window-d654a3e44a855e9b.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libglutin-ca9e57202d2cb0ad.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libshared_library-f4ac2cf3cc1e9597.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libpiston-fd6dc79ad82016b4.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgfx_graphics-7f468e12bc913cff.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgfx_texture-5720e2ea52c1d3df.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libimage-e7f2d20ae47bfb08.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libuser32-dc94dabda4876d9a.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libevent_loop-17f635dfb1b44576.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libwindow-ad67fd2b615641f5.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libshader_version-f684e92d2d314f91.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libfreetype-7b4c87beabcd8fe7.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libpng-4b704d4773932522.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libflate2-f631189bcf5818ae.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libminiz_sys-f1c39e8e406fa25f.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libdwmapi-9ad49f05afcefc91.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libinput-ce8af36c334a0d0b.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgl-caccb99a7fc8e33d.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libfreetype_sys-5dbe1f179da1057a.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libinflate-b852113d32258b7b.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libshell32-7fc5728fe7652dea.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libdaggy-15bbe9f17d4bad73.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libpetgraph-6f64e652e095d54e.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libfixedbitset-691631c044f57fb9.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgfx_device_gl-d32c04808be1031a.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgfx_gl-25b339f39da46849.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libtime-b8d9c9e7ca5bced7.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libenum_primitive-f59ab0a46937bdae.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgdi32-5ec2c9d6697f647a.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgfx-b43b9d4ddc03f960.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libnum-1ef9aa8d582358bc.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\librand-204b49f864ff4762.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libadvapi32-cfef7a1f30f1e5f6.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\librustc_serialize-7ff5bfc027146194.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libshaders_graphics2d-bb347d3b5d5c0137.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\liblazy_static-f3aa6dfcc7c157cc.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libkernel32-35c1a745c861d23a.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libwinapi-d88a8c018c340227.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libbyteorder-8489290bbd10b018.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgif-349733e89c61a899.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libcolor_quant-6695fde28ee2e395.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\liblzw-b298258ca3ee8886.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libgraphics-4666253153b9ad9d.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libdraw_state-8219476462483b29.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libread_color-309218e52cd2ef95.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libtexture-1c413c5bbaf9401a.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libvecmath-9b5adf5764bff9e1.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libbitflags-eec34728826d9769.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libinterpolation-ee7e041bd12b608b.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libviewport-2fa528cee63f2915.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\libfloat-5e49744bf68c9774.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\liblog-db195e915b7f1b50.rlib" "C:\\dev\\testgui\\target\\debug\\deps\\liblibc-53b3109cf33a6ace.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcollections-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_unicode-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\librand-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-35c36e89.rlib" "opengl32.lib" "user32.lib" "dwmapi.lib" "freetype.lib" "shell32.lib" "gdi32.lib" "advapi32.lib" "kernel32.lib" "msvcrt.lib" "ws2_32.lib" "userenv.lib" "advapi32.lib" "kernel32.lib" "shell32.lib" "msvcrt.lib" "compiler-rt.lib"
note: testgui.0.o : error LNK2019: unresolved external symbol FT_New_Face referenced in function _ZN7library13_$LT$impl$GT$8new_face8new_face20h4160429053330431212E
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Reference_Library referenced in function _ZN4face13_$LT$impl$GT$5clone20hd2f3fbcb85dcc460BPbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Reference_Face referenced in function _ZN4face13_$LT$impl$GT$5clone20hd2f3fbcb85dcc460BPbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Attach_File referenced in function _ZN4face13_$LT$impl$GT$11attach_file20hdbb984a85167ead5tRbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Set_Char_Size referenced in function _ZN4face13_$LT$impl$GT$13set_char_size20h09d2a3cc2d67521fCSbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Set_Pixel_Sizes referenced in function _ZN4face13_$LT$impl$GT$15set_pixel_sizes20h706809c7a575cb33rTbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Load_Glyph referenced in function _ZN4face13_$LT$impl$GT$10load_glyph20h6ef7425a8e9abf074TbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Load_Char referenced in function _ZN4face13_$LT$impl$GT$9load_char20h66875f818ab9bd55IUbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Set_Transform referenced in function _ZN4face13_$LT$impl$GT$13set_transform20h3c75d36e4e08d102oVbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Get_Char_Index referenced in function _ZN4face13_$LT$impl$GT$14get_char_index20hdbde7d4a34280b68LVbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Get_Kerning referenced in function _ZN4face13_$LT$impl$GT$11get_kerning20hd5e94e508d9280764VbE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b5c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Get_Postscript_Name referenced in function _ZN4face13_$LT$impl$GT$15postscript_name20hf62cc25c5e90308bg3bE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Done_Face referenced in function _ZN4face13_$LT$impl$GT$4drop20ha6a23216654714e2K4bE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Done_Library referenced in function _ZN4face13_$LT$impl$GT$4drop20ha6a23216654714e2K4bE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Glyph_Transform referenced in function _ZN5glyph13_$LT$impl$GT$9transform20hb432d30c0a7924b3E6bE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-6b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Glyph_Get_CBox referenced in function _ZN5glyph13_$LT$impl$GT$8get_cbox20hffc2f666d7d035aaT7bE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Glyph_To_Bitmap referenced in function _ZN5glyph13_$LT$impl$GT$9to_bitmap20hfd5aa88646d19d50m8bE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Glyph_Copy referenced in function _ZN5glyph13_$LT$impl$GT$5clone20ha4e07eda6bc22936xacE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Done_Glyph referenced in function _ZN5glyph13_$LT$impl$GT$4drop20h40c3a8cb12e16a5atbcE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Render_Glyph referenced in function _ZN10glyph_slot13_$LT$impl$GT$12render_glyph20h6fb3e3d6e63288b0bhcE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Get_SubGlyph_Info referenced in function _ZN10glyph_slot13_$LT$impl$GT$17get_subglyph_info20h63bdec2823a0aa3eMhcE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Get_Glyph referenced in function _ZN10glyph_slot13_$LT$impl$GT$9get_glyph20h4b45bb351f4002cbFicE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_New_Library referenced in function _ZN7library13_$LT$impl$GT$4init20h370ddb438430955dBncE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_Add_Default_Modules referenced in function _ZN7library13_$LT$impl$GT$4init20h370ddb438430955dBncE
libfreetype-7b4c87beabcd8fe7.rlib(freetype-7b4c87beabcd8fe7.0.o) : error LNK2019: unresolved external symbol FT_New_Memory_Face referenced in function _ZN7library13_$LT$impl$GT$15new_memory_face20h5543fde1bae245f0KpcE
C:\dev\testgui\target\debug\testgui.exe : fatal error LNK1120: 25 unresolved externals

error: aborting due to previous error
Could not compile `testgui`.

To learn more, run the command again with --verbose.
</pre>

**Comment by tomaka** [comment]
I don't know exactly what you're doing, but your title says `MSVC ABI and GnuWin32 freetype.lib`. If you use MSVC, then the GNU freetype.lib is not compatible.

Are you using these binaries: https://github.com/PistonDevelopers/binaries/tree/master/x86_64 ?
