### ISSUE TITLE
Unable to Build On Windows With MinGw

### ISSUE THREAD

**Issue by yeliknewo** [PistonDevelopers/freetype-sys#55]
I got Msys2 and I used pacman to install freetype. I installed the mingw seperately like it says to in the rust repo. When I try to link piston it gives me the error 
ld: cannot find -lfreetype-6
I looked around a bit but I can't seem to find what I am doing wrong.

**Comment by jhasse** [comment]
#56 should fix this :)

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/freetype-sys/pull/56
