### ISSUE TITLE
FT_Get_Sfnt_Table only available on Linux and OSX

### ISSUE THREAD

**Issue by Osspial** [PistonDevelopers/freetype-sys#70]
The `FT_Get_Sfnt_Table` function is currently in its own `extern` block separate from all the other functions, marked with `#[cfg(any(target_os = "linux", target_os = "macos"))]`. This would be fairly easy to fix, but why was this restriction made in the first place? Removing the tag and calling the function seems to work on my Windows 10 machine, and I don't see any OS restrictions in the FreeType source code.

@bvssvni

**Comment by bvssvni** [comment]
It was a problem on Windows 8.1 x64 back when the code was in freetype-rs. See https://github.com/PistonDevelopers/freetype-rs/issues/160

Perhaps this was a problem with an old version of FreeType?

@johansfrids Are you able to test this?

**Comment by waywardmonkeys** [comment]
This is no longer the case and this is unconditionally available.

**Comment by bvssvni** [comment]
Closing.
