### ISSUE TITLE
Can't find freetype.dll despite having a config file etc. 

### ISSUE THREAD

**Issue by tensor-programming** [PistonDevelopers/freetype-sys#71]
I'm trying to build on windows with MSVC.  I got the binaries and put a `.cargo/config` file in my project with these flags: 
`[target.x86_64-pc-windows-msvc.freetype]
rustc-link-search = ["C:\\freetype\\x86_64"]
rustc-link-lib = ["freetype"]`

My freetype.dll is inside of the directory specified but I get this error when I try to build the project, `The code execution cannot proceed because freetype.dll was not found.  Reinstalling the program may fix this problem.  

Any Ideas on how to fix this?  I've tried re-downloading the dlls etc but its the same error.

**Comment by tomaka** [comment]
At compile-time, you need a `freetype.lib`, not `dll`.

**Comment by tensor-programming** [comment]
I have the lib in the same folder as the dll, it is the compiled distribution from the instructions so it has freetype.dll freetype.dll.asc freetype.lib and freetype.lib.asc inside of the same folder.  Do i need to separate them or make another reference in the cargo/configure file to link it correctly?  There is no mention of this in the instructions.

**Comment by tensor-programming** [comment]
I was able to get it to work by taking the files and copying them directly into my toolchain library path.  you should really fix the instructions.
